### ISSUE TITLE
Error when trying to set GEO visibility from file uploads

### ISSUE THREAD

**Issue by lostfocus** [dshanske/simple-location#252]
I just tried to upload a file with this plugin installed and I got this error:

```
Error Details
=============
An error of type E_ERROR was caused in line 233 of the file /var/www/wordpress/wp-content/plugins/simple-location/includes/class-sloc-media-metadata.php. Error message: Uncaught Error: Call to undefined function set_geo_visibility() in /var/www/wordpress/wp-content/plugins/simple-location/includes/class-sloc-media-metadata.php:233
Stack trace:
#0 /var/www/wordpress/wp-includes/class-wp-hook.php(310): Sloc_Media_Metadata::attachment()
#1 /var/www/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/wordpress/wp-admin/includes/image.php(658): apply_filters()
#3 /var/www/wordpress/wp-admin/includes/media.php(430): wp_generate_attachment_metadata()
#4 /var/www/wordpress/wp-admin/async-upload.php(114): media_handle_upload()
#5 {main}
  thrown
```

Because WP can't generate the metadata, it will also not create the thumbnails, which is a bit unfortunate.

WordPress version 6.1.1
Current plugin: Simple Location (version 5.0.8)
PHP version 8.2.1

**Comment by dshanske** [comment]
Will look into and fix

**Comment by dshanske** [comment]
Should be addressed now. New version 5.0.10

**Comment by lostfocus** [comment]
Oh, thanks for the quick fix! Indeed I don't get that error message anymore.  
It's still not generating the thumbnails because it seems to not save the file metadata. (I tried the same with the same file and the same WordPress but with this plugin disabled and it worked.)
It's probably helpful to know that this is happening with iOS screenshots - so PNG files without any embedded geo data.

Uploading JPGs with geodata works well with and without the plugin, but in the edit screen I get this error message:

<img width="295" alt="Screenshot 2023-03-13 at 13 15 14" src="https://user-images.githubusercontent.com/45055/224699175-2201ed65-6922-489e-880c-1ac236252e23.png">

and an email with this error:

```
An error of type E_ERROR was caused in line 40 of the file /var/www/wordpress/wp-content/plugins/simple-location/templates/loc-metabox.php. Error message: Uncaught Error: Call to a member function set() on null in /var/www/wordpress/wp-content/plugins/simple-location/templates/loc-metabox.php:40
Stack trace:
#0 /var/www/wordpress/wp-includes/template.php(783): require_once()
#1 /var/www/wordpress/wp-content/plugins/simple-location/includes/class-geo-base.php(119): load_template()
#2 /var/www/wordpress/wp-admin/includes/template.php(1409): Geo_Base::metabox()
#3 /var/www/wordpress/wp-admin/edit-form-advanced.php(681): do_meta_boxes()
#4 /var/www/wordpress/wp-admin/post.php(206): require('...')
#5 {main}
  thrown
```

**Comment by dshanske** [comment]
Will check... I rewrote the GPS code last week because it wasn't triggering on EXIF version 2.32, may have introduced a bug if there isn't any.

**Comment by dshanske** [comment]
@lostfocus  A set issue on NULL means you don't have a map provider set. I'll add a check. Do you have one set?

**Comment by lostfocus** [comment]
No, I don't have a map provider set

**Comment by dshanske** [comment]
I pushed a fix for this, will be in the next release. If you want to try dev, it is there.
